// AUTO-GENERATED: Do not edit manually. Generated from content/recipe-images.json

export const recipeImages = {
  'steak-garlic-butter-potatoes': require('../../assets/recipes/steak-garlic-butter-potatoes.jpg'),
  'detroit-style-pizza': require('../../assets/recipes/detroit-style-pizza.jpg'),
  'buttermilk-fried-chicken': require('../../assets/recipes/buttermilk-fried-chicken.jpg'),
  'bbq-ribs-oven-finish': require('../../assets/recipes/bbq-ribs-oven-finish.jpg'),
  'chicken-pot-pie': require('../../assets/recipes/chicken-pot-pie.jpg'),
  'spaghetti-meatballs': require('../../assets/recipes/spaghetti-meatballs.jpg'),
  'philly-cheesesteak': require('../../assets/recipes/philly-cheesesteak.jpg'),
  'tex-mex-fajitas': require('../../assets/recipes/tex-mex-fajitas.jpg'),
  'classic-cheeseburger': require('../../assets/recipes/classic-cheeseburger.jpg'),
  'pizza-sheet-pan-shortcut': require('../../assets/recipes/pizza-sheet-pan-shortcut.jpg'),
  'blt-sandwich': require('../../assets/recipes/blt-sandwich.jpg'),
  'mac-cheese': require('../../assets/recipes/mac-cheese.jpg'),
  'mashed-potatoes': require('../../assets/recipes/mashed-potatoes.jpg'),
  'tacos': require('../../assets/recipes/tacos.jpg'),
  'chili-basic': require('../../assets/recipes/chili-basic.jpg'),
  'french-fries-oven': require('../../assets/recipes/french-fries-oven.jpg'),
  'instant-ramen': require('../../assets/recipes/instant-ramen.jpg'),
  'scrambled-eggs-toast': require('../../assets/recipes/scrambled-eggs-toast.jpg'),
  'rice-beans': require('../../assets/recipes/rice-beans.jpg'),
  'pasta-aglio-olio': require('../../assets/recipes/pasta-aglio-olio.jpg'),
  'canned-tuna-sandwich': require('../../assets/recipes/canned-tuna-sandwich.jpg'),
  'rice-bowl': require('../../assets/recipes/rice-bowl.jpg'),
  'pasta-red-sauce': require('../../assets/recipes/pasta-red-sauce.jpg'),
  'quesadillas': require('../../assets/recipes/quesadillas.jpg'),
  'grilled-cheese': require('../../assets/recipes/grilled-cheese.jpg'),
  'sandwich-bar': require('../../assets/recipes/sandwich-bar.jpg'),
  'pizza-frozen-fast': require('../../assets/recipes/pizza-frozen-fast.jpg'),
  'breakfast-for-dinner': require('../../assets/recipes/breakfast-for-dinner.jpg'),
  'lightning-chili': require('../../assets/recipes/lightning-chili.jpg'),
  'chicken-noodle-soup': require('../../assets/recipes/chicken-noodle-soup.jpg'),
  'thursday-night-soup': require('../../assets/recipes/thursday-night-soup.jpg'),
  'easy-nachos': require('../../assets/recipes/easy-nachos.jpg'),
  'spicy-beef-ramen': require('../../assets/recipes/spicy-beef-ramen.jpg'),
};
