export interface Recipe {
  id: string;
  name: string;
  category: 'fancy' | 'easy' | 'cheap' | 'rescue';
  steps: string[];
  ingredients: string[];
}

export const recipes: Recipe[] = [
  // ============= FANCY (8) =============
  {
    id: 'steak-garlic-butter-potatoes',
    name: 'Steak & Garlic Butter Potatoes',
    category: 'fancy',
    ingredients: ['Steak', 'Potatoes', 'Butter', 'Garlic', 'Salt', 'Pepper'],
    steps: [
      'Season steak (salt + pepper), rest 10 min',
      'Sear 3–4 min per side in hot pan',
      'Add butter, garlic, herbs → baste',
      'Roast potatoes (olive oil + salt, 425°F)',
      'Rest steak, slice, serve',
    ],
  },
  {
    id: 'detroit-style-pizza',
    name: 'Detroit-Style Pizza',
    category: 'fancy',
    ingredients: ['Dough', 'Mozzarella cheese', 'Pizza sauce', 'Pepperoni (optional)', 'Olive oil'],
    steps: [
      'Press dough into oiled rectangular pan',
      'Layer cheese edge-to-edge',
      'Add toppings (pepperoni, etc.)',
      'Bake until crispy edges form',
      'Spoon sauce on top, slice',
    ],
  },
  {
    id: 'buttermilk-fried-chicken',
    name: 'Buttermilk Fried Chicken',
    category: 'fancy',
    ingredients: ['Chicken', 'Buttermilk', 'Flour', 'Oil', 'Salt', 'Pepper', 'Paprika'],
    steps: [
      'Marinate chicken in buttermilk + spices',
      'Dredge in seasoned flour',
      'Fry until golden and crispy',
      'Rest on rack (not paper towels)',
      'Serve hot',
    ],
  },
  {
    id: 'bbq-ribs-oven-finish',
    name: 'BBQ Ribs (Oven + Finish)',
    category: 'fancy',
    ingredients: ['Pork ribs', 'BBQ sauce', 'Brown sugar', 'Salt', 'Pepper', 'Garlic powder'],
    steps: [
      'Season ribs (dry rub)',
      'Wrap + bake low (275°F, 2.5–3 hrs)',
      'Unwrap, brush BBQ sauce',
      'Broil or grill for caramelization',
      'Rest, slice',
    ],
  },
  {
    id: 'chicken-pot-pie',
    name: 'Chicken Pot Pie',
    category: 'fancy',
    ingredients: ['Chicken', 'Frozen mixed veggies', 'Pie crust', 'Butter', 'Milk or cream'],
    steps: [
      'Cook chicken + veggies in skillet',
      'Add cream sauce (butter + flour + broth)',
      'Pour into dish',
      'Top with crust',
      'Bake until golden',
    ],
  },
  {
    id: 'spaghetti-meatballs',
    name: 'Spaghetti & Meatballs',
    category: 'fancy',
    ingredients: ['Ground beef', 'Pasta', 'Tomato sauce', 'Egg', 'Breadcrumbs'],
    steps: [
      'Mix meatballs (beef, breadcrumbs, egg)',
      'Brown meatballs',
      'Simmer in tomato sauce',
      'Boil pasta',
      'Combine + serve',
    ],
  },
  {
    id: 'philly-cheesesteak',
    name: 'Philly Cheesesteak',
    category: 'fancy',
    ingredients: ['Steak (thin sliced)', 'Hoagie rolls', 'Cheese (provolone/whiz)', 'Onion', 'Bell pepper'],
    steps: [
      'Slice steak thin',
      'Cook onions + peppers',
      'Sear steak quickly',
      'Add cheese (provolone/whiz)',
      'Load into toasted roll',
    ],
  },
  {
    id: 'tex-mex-fajitas',
    name: 'Tex-Mex Fajitas',
    category: 'fancy',
    ingredients: ['Chicken or steak', 'Bell peppers', 'Onion', 'Tortillas', 'Fajita seasoning'],
    steps: [
      'Marinate steak/chicken',
      'Sear hot (cast iron preferred)',
      'Cook peppers + onions',
      'Warm tortillas',
      'Assemble',
    ],
  },

  // ============= EASY (8) =============
  {
    id: 'classic-cheeseburger',
    name: 'Classic Cheeseburger',
    category: 'easy',
    ingredients: ['Ground beef', 'Buns', 'Cheese', 'Lettuce', 'Tomato'],
    steps: [
      'Form patties',
      'Salt + sear',
      'Flip once, add cheese',
      'Toast buns',
      'Assemble',
    ],
  },
  {
    id: 'pizza-sheet-pan-shortcut',
    name: 'Pizza (Sheet Pan Shortcut)',
    category: 'easy',
    ingredients: ['Flatbread or dough', 'Sauce', 'Cheese', 'Toppings (optional)'],
    steps: [
      'Use store dough or flatbread',
      'Add sauce',
      'Add cheese + toppings',
      'Bake until melted',
      'Slice',
    ],
  },
  {
    id: 'blt-sandwich',
    name: 'BLT Sandwich',
    category: 'easy',
    ingredients: ['Bacon', 'Bread', 'Lettuce', 'Tomato', 'Mayo'],
    steps: [
      'Cook bacon',
      'Toast bread',
      'Add mayo',
      'Layer bacon, lettuce, tomato',
      'Close + slice',
    ],
  },
  {
    id: 'mac-cheese',
    name: 'Mac & Cheese',
    category: 'easy',
    ingredients: ['Pasta', 'Cheese', 'Milk', 'Butter'],
    steps: [
      'Boil pasta',
      'Melt butter + milk',
      'Add shredded cheese',
      'Mix pasta',
      'Serve',
    ],
  },
  {
    id: 'mashed-potatoes',
    name: 'Mashed Potatoes',
    category: 'easy',
    ingredients: ['Potatoes', 'Butter', 'Milk', 'Salt'],
    steps: [
      'Boil potatoes',
      'Drain + mash',
      'Add butter + milk',
      'Salt',
      'Mix',
    ],
  },
  {
    id: 'tacos',
    name: 'Tacos',
    category: 'easy',
    ingredients: ['Ground beef', 'Taco seasoning', 'Tortillas', 'Cheese', 'Lettuce'],
    steps: [
      'Brown ground beef',
      'Add seasoning',
      'Warm shells',
      'Add toppings',
      'Serve',
    ],
  },
  {
    id: 'chili-basic',
    name: 'Chili (Basic)',
    category: 'easy',
    ingredients: ['Ground beef', 'Beans', 'Canned tomatoes', 'Chili seasoning'],
    steps: [
      'Brown meat',
      'Add beans + tomatoes',
      'Add seasoning',
      'Simmer',
      'Serve',
    ],
  },
  {
    id: 'french-fries-oven',
    name: 'French Fries (Oven)',
    category: 'easy',
    ingredients: ['Potatoes', 'Oil', 'Salt'],
    steps: [
      'Cut potatoes',
      'Toss in oil + salt',
      'Bake 425°F',
      'Flip halfway',
      'Crisp + serve',
    ],
  },

  // ============= CHEAP (5) =============
  {
    id: 'instant-ramen',
    name: 'Instant Ramen',
    category: 'cheap',
    ingredients: ['Ramen packet', 'Water', 'Egg (optional)', 'Green onion (optional)'],
    steps: [
      'Boil water',
      'Add ramen + seasoning packet',
      'Boil 3 min',
      'Add egg if desired',
      'Serve hot',
    ],
  },
  {
    id: 'scrambled-eggs-toast',
    name: 'Scrambled Eggs & Toast',
    category: 'cheap',
    ingredients: ['Eggs', 'Bread', 'Butter', 'Salt', 'Pepper'],
    steps: [
      'Crack eggs in bowl',
      'Toast bread',
      'Scramble eggs in butter',
      'Season',
      'Serve together',
    ],
  },
  {
    id: 'rice-beans',
    name: 'Rice & Beans',
    category: 'cheap',
    ingredients: ['Rice', 'Canned beans', 'Salt', 'Onion (optional)', 'Garlic (optional)'],
    steps: [
      'Cook rice',
      'Heat canned beans',
      'Combine',
      'Season',
      'Serve',
    ],
  },
  {
    id: 'pasta-aglio-olio',
    name: 'Pasta Aglio e Olio',
    category: 'cheap',
    ingredients: ['Pasta', 'Garlic', 'Olive oil', 'Red pepper flakes', 'Salt'],
    steps: [
      'Boil pasta',
      'Heat oil + sliced garlic',
      'Add red pepper flakes',
      'Toss pasta with oil',
      'Serve',
    ],
  },
  {
    id: 'canned-tuna-sandwich',
    name: 'Canned Tuna Sandwich',
    category: 'cheap',
    ingredients: ['Canned tuna', 'Bread', 'Mayo', 'Lettuce', 'Tomato'],
    steps: [
      'Drain tuna',
      'Mix tuna + mayo',
      'Toast bread',
      'Spread tuna mixture',
      'Add lettuce + tomato, close + serve',
    ],
  },

  // ============= RESCUE (12) =============
  {
    id: 'rice-bowl',
    name: 'Rice Bowl',
    category: 'rescue',
    ingredients: ['Rice', 'Protein (chicken/beef/eggs)', 'Sauce (soy, teriyaki, etc.)', 'Frozen veggies'],
    steps: [
      'Cook rice',
      'Add protein (leftover or quick cook)',
      'Add sauce',
      'Add veggies',
      'Mix',
    ],
  },
  {
    id: 'pasta-red-sauce',
    name: 'Pasta + Red Sauce',
    category: 'rescue',
    ingredients: ['Pasta', 'Jarred sauce', 'Parmesan'],
    steps: [
      'Boil pasta',
      'Heat jar sauce',
      'Combine',
      'Add cheese',
      'Serve',
    ],
  },
  {
    id: 'quesadillas',
    name: 'Quesadillas',
    category: 'rescue',
    ingredients: ['Tortillas', 'Cheese', 'Protein (optional)'],
    steps: [
      'Add cheese to tortilla',
      'Add protein (optional)',
      'Fold',
      'Cook both sides',
      'Slice',
    ],
  },
  {
    id: 'grilled-cheese',
    name: 'Grilled Cheese',
    category: 'rescue',
    ingredients: ['Bread', 'Cheese', 'Butter'],
    steps: [
      'Butter bread',
      'Add cheese',
      'Cook both sides',
      'Press lightly',
      'Slice',
    ],
  },
  {
    id: 'sandwich-bar',
    name: 'Sandwich Bar',
    category: 'rescue',
    ingredients: ['Bread', 'Deli meat', 'Cheese', 'Lettuce', 'Condiments'],
    steps: [
      'Lay out bread',
      'Add meats',
      'Add cheese',
      'Add toppings',
      'Assemble',
    ],
  },
  {
    id: 'pizza-frozen-fast',
    name: 'Pizza (Frozen or Fast)',
    category: 'rescue',
    ingredients: ['Frozen pizza or dough'],
    steps: [
      'Preheat oven',
      'Add pizza',
      'Bake',
      'Slice',
      'Serve',
    ],
  },
  {
    id: 'breakfast-for-dinner',
    name: 'Breakfast for Dinner',
    category: 'rescue',
    ingredients: ['Eggs', 'Bread', 'Bacon or sausage'],
    steps: [
      'Cook eggs',
      'Toast bread',
      'Cook bacon/sausage',
      'Plate',
      'Serve',
    ],
  },
  {
    id: 'lightning-chili',
    name: 'Lightning Chili',
    category: 'rescue',
    ingredients: ['Ground beef', 'Canned chili/beans', 'Seasoning'],
    steps: [
      'Brown meat',
      'Add canned chili or beans',
      'Add seasoning',
      'Simmer 10–15 min',
      'Serve',
    ],
  },
  {
    id: 'chicken-noodle-soup',
    name: 'Chicken Noodle Soup',
    category: 'rescue',
    ingredients: ['Chicken', 'Noodles', 'Broth', 'Carrots', 'Celery'],
    steps: [
      'Boil broth',
      'Add noodles',
      'Add chicken',
      'Add veggies',
      'Simmer',
    ],
  },
  {
    id: 'thursday-night-soup',
    name: 'Thursday Night Soup (Leftover Soup)',
    category: 'rescue',
    ingredients: ['Leftovers', 'Broth', 'Seasoning'],
    steps: [
      'Combine leftovers',
      'Add broth',
      'Heat',
      'Season',
      'Serve',
    ],
  },
  {
    id: 'easy-nachos',
    name: 'Easy Nachos',
    category: 'rescue',
    ingredients: ['Chips', 'Cheese', 'Beans or meat', 'Salsa'],
    steps: [
      'Lay chips',
      'Add cheese',
      'Add meat/beans',
      'Bake/microwave',
      'Add toppings',
    ],
  },
  {
    id: 'spicy-beef-ramen',
    name: 'Spicy Beef Ramen',
    category: 'rescue',
    ingredients: ['Ramen noodles', 'Ground beef', 'Broth', 'Chili paste or seasoning'],
    steps: [
      'Boil noodles',
      'Cook beef',
      'Add seasoning + broth',
      'Combine',
      'Add egg (optional)',
    ],
  },
];
