/**
 * Seed Recipes + DRM Meals
 * 
 * MVP seed data for offline card dealing.
 * - 6 recipes per mode (fancy/easy/cheap)
 * - At least 1 vegetarian per mode
 * - 12 DRM panic meals
 */

import type { RecipeSeed, DrmSeed } from './types';

export const RECIPES: RecipeSeed[] = [
  // ============================================
  // FANCY MODE (6 items, 2 vegetarian)
  // ============================================
  {
    id: 'fancy-1',
    name: 'Pan-Seared Salmon',
    mode: 'fancy',
    vegetarian: false,
    allergens: [],
    constraints: [],
    ingredients: [
      { name: 'Salmon fillet', quantity: '2 pieces' },
      { name: 'Lemon', quantity: '1' },
      { name: 'Butter', quantity: '2 tbsp' },
      { name: 'Fresh dill', quantity: 'handful' },
    ],
    steps: [
      'Pat salmon dry, season with salt and pepper',
      'Heat pan with butter over medium-high',
      'Sear skin-side down for 4 minutes',
      'Flip and cook 3 more minutes',
      'Squeeze lemon, garnish with dill',
    ],
    whyReasons: ['Restaurant quality at home', 'Omega-3 rich', 'Under 20 minutes'],
    estimatedTime: '18 min',
    estimatedCost: '$22',
    emoji: '🐟',
    imageKey: 'salmon',
  },
  {
    id: 'fancy-2',
    name: 'Mushroom Risotto',
    mode: 'fancy',
    vegetarian: true,
    allergens: ['dairy'],
    constraints: ['vegetarian'],
    ingredients: [
      { name: 'Arborio rice', quantity: '1.5 cups' },
      { name: 'Mixed mushrooms', quantity: '8 oz' },
      { name: 'White wine', quantity: '1/2 cup' },
      { name: 'Parmesan', quantity: '1/2 cup grated' },
      { name: 'Vegetable broth', quantity: '4 cups' },
    ],
    steps: [
      'Sauté mushrooms until golden, set aside',
      'Toast rice in butter for 2 minutes',
      'Add wine, stir until absorbed',
      'Add broth one ladle at a time, stirring',
      'Fold in mushrooms and parmesan',
    ],
    whyReasons: ['Comfort food elevated', 'Vegetarian crowd-pleaser', 'Creamy without cream'],
    estimatedTime: '35 min',
    estimatedCost: '$18',
    imageKey: 'risotto',
  },
  {
    id: 'fancy-3',
    name: 'Herb-Crusted Chicken',
    mode: 'fancy',
    vegetarian: false,
    allergens: ['gluten'],
    constraints: [],
    ingredients: [
      { name: 'Chicken breast', quantity: '2' },
      { name: 'Breadcrumbs', quantity: '1 cup' },
      { name: 'Fresh herbs', quantity: 'mixed' },
      { name: 'Dijon mustard', quantity: '2 tbsp' },
    ],
    steps: [
      'Preheat oven to 400°F',
      'Brush chicken with mustard',
      'Press herb-breadcrumb mixture onto chicken',
      'Bake for 25 minutes until golden',
    ],
    whyReasons: ['Impressive but simple', 'Fresh herbs shine', 'Pairs with anything'],
    estimatedTime: '35 min',
    estimatedCost: '$16',
    imageKey: 'chicken-marsala',
  },
  {
    id: 'fancy-4',
    name: 'Shrimp Scampi',
    mode: 'fancy',
    vegetarian: false,
    allergens: ['shellfish', 'gluten'],
    constraints: ['15_min'],
    ingredients: [
      { name: 'Large shrimp', quantity: '1 lb' },
      { name: 'Linguine', quantity: '8 oz' },
      { name: 'Garlic', quantity: '6 cloves' },
      { name: 'White wine', quantity: '1/2 cup' },
      { name: 'Butter', quantity: '4 tbsp' },
    ],
    steps: [
      'Cook pasta al dente',
      'Sauté garlic in butter until fragrant',
      'Add shrimp, cook 2 minutes per side',
      'Deglaze with wine, toss with pasta',
    ],
    whyReasons: ['Date night ready', 'Garlic butter magic', 'Fast yet fancy'],
    estimatedTime: '15 min',
    estimatedCost: '$24',
    imageKey: 'scampi',
  },
  {
    id: 'fancy-5',
    name: 'Beef Tenderloin',
    mode: 'fancy',
    vegetarian: false,
    allergens: [],
    constraints: [],
    ingredients: [
      { name: 'Beef tenderloin', quantity: '2 steaks' },
      { name: 'Rosemary', quantity: '2 sprigs' },
      { name: 'Garlic', quantity: '4 cloves' },
      { name: 'Butter', quantity: '3 tbsp' },
    ],
    steps: [
      'Bring steaks to room temperature',
      'Season generously with salt and pepper',
      'Sear in hot pan 3-4 minutes per side',
      'Baste with butter, garlic, rosemary',
      'Rest 5 minutes before serving',
    ],
    whyReasons: ['Steakhouse at home', 'Perfect medium-rare', 'Worth the splurge'],
    estimatedTime: '25 min',
    estimatedCost: '$35',
    imageKey: 'steak',
  },
  {
    id: 'fancy-6',
    name: 'Caprese Stack',
    mode: 'fancy',
    vegetarian: true,
    allergens: ['dairy'],
    constraints: ['vegetarian', 'no_oven', '15_min'],
    ingredients: [
      { name: 'Fresh mozzarella', quantity: '8 oz' },
      { name: 'Heirloom tomatoes', quantity: '2 large' },
      { name: 'Fresh basil', quantity: 'large bunch' },
      { name: 'Balsamic glaze', quantity: '2 tbsp' },
    ],
    steps: [
      'Slice mozzarella and tomatoes evenly',
      'Stack alternating layers',
      'Tuck basil leaves between',
      'Drizzle with olive oil and balsamic',
    ],
    whyReasons: ['No cooking required', 'Summer on a plate', 'Instagram-ready'],
    estimatedTime: '10 min',
    estimatedCost: '$14',
    imageKey: 'ratatouille',
  },

  // ============================================
  // EASY MODE (6 items, 2 vegetarian)
  // ============================================
  {
    id: 'easy-1',
    name: 'Sheet Pan Chicken',
    mode: 'easy',
    vegetarian: false,
    allergens: [],
    constraints: [],
    ingredients: [
      { name: 'Chicken thighs', quantity: '4' },
      { name: 'Baby potatoes', quantity: '1 lb' },
      { name: 'Broccoli', quantity: '2 cups' },
      { name: 'Olive oil', quantity: '3 tbsp' },
    ],
    steps: [
      'Preheat oven to 425°F',
      'Toss everything with oil and seasoning',
      'Spread on sheet pan',
      'Roast 35 minutes',
    ],
    whyReasons: ['One pan, one cleanup', 'Set it and forget it', 'Balanced meal'],
    estimatedTime: '40 min',
    estimatedCost: '$14',
    imageKey: 'sheet-pan-chicken',
  },
  {
    id: 'easy-2',
    name: 'Pasta Marinara',
    mode: 'easy',
    vegetarian: true,
    allergens: ['gluten'],
    constraints: ['vegetarian', '15_min'],
    ingredients: [
      { name: 'Spaghetti', quantity: '12 oz' },
      { name: 'Marinara sauce', quantity: '24 oz jar' },
      { name: 'Parmesan', quantity: '1/4 cup' },
      { name: 'Fresh basil', quantity: 'handful' },
    ],
    steps: [
      'Boil pasta according to package',
      'Heat marinara in separate pan',
      'Drain pasta, toss with sauce',
      'Top with parmesan and basil',
    ],
    whyReasons: ['Pantry staples', 'Kid-approved', 'Ready in 15'],
    estimatedTime: '15 min',
    estimatedCost: '$8',
    imageKey: 'pasta-marinara',
  },
  {
    id: 'easy-3',
    name: 'Quesadillas',
    mode: 'easy',
    vegetarian: false,
    allergens: ['dairy', 'gluten'],
    constraints: ['15_min', 'kid_safe'],
    ingredients: [
      { name: 'Flour tortillas', quantity: '4' },
      { name: 'Shredded cheese', quantity: '2 cups' },
      { name: 'Rotisserie chicken', quantity: '1 cup shredded' },
      { name: 'Salsa', quantity: 'for serving' },
    ],
    steps: [
      'Layer cheese and chicken on tortilla',
      'Fold and press in dry pan',
      'Cook 3 minutes per side until crispy',
      'Cut into wedges, serve with salsa',
    ],
    whyReasons: ['Kids love it', 'Uses leftover chicken', 'Crispy and melty'],
    estimatedTime: '12 min',
    estimatedCost: '$10',
    imageKey: 'quesadillas',
  },
  {
    id: 'easy-4',
    name: 'Stir-Fry Rice',
    mode: 'easy',
    vegetarian: true,
    allergens: ['soy', 'eggs'],
    constraints: ['vegetarian', '15_min'],
    ingredients: [
      { name: 'Leftover rice', quantity: '3 cups' },
      { name: 'Eggs', quantity: '2' },
      { name: 'Frozen peas', quantity: '1 cup' },
      { name: 'Soy sauce', quantity: '3 tbsp' },
    ],
    steps: [
      'Scramble eggs in hot wok, set aside',
      'Stir-fry rice over high heat',
      'Add peas and soy sauce',
      'Fold in eggs, serve hot',
    ],
    whyReasons: ['Uses leftovers', 'Protein-packed', 'Better than takeout'],
    estimatedTime: '12 min',
    estimatedCost: '$5',
    imageKey: 'stir-fry',
  },
  {
    id: 'easy-5',
    name: 'Taco Night',
    mode: 'easy',
    vegetarian: false,
    allergens: ['dairy'],
    constraints: ['kid_safe'],
    ingredients: [
      { name: 'Ground beef', quantity: '1 lb' },
      { name: 'Taco seasoning', quantity: '1 packet' },
      { name: 'Taco shells', quantity: '12' },
      { name: 'Toppings', quantity: 'cheese, lettuce, tomato' },
    ],
    steps: [
      'Brown beef, drain fat',
      'Add seasoning and water, simmer 5 min',
      'Warm shells in oven',
      'Set up toppings bar, let everyone build',
    ],
    whyReasons: ['Family favorite', 'Everyone customizes', 'Fast crowd-pleaser'],
    estimatedTime: '20 min',
    estimatedCost: '$15',
    imageKey: 'fried-rice',
  },
  {
    id: 'easy-6',
    name: 'Grilled Cheese & Soup',
    mode: 'easy',
    vegetarian: true,
    allergens: ['dairy', 'gluten'],
    constraints: ['vegetarian', '15_min', 'kid_safe'],
    ingredients: [
      { name: 'Bread', quantity: '4 slices' },
      { name: 'Cheddar cheese', quantity: '4 slices' },
      { name: 'Butter', quantity: '2 tbsp' },
      { name: 'Tomato soup', quantity: '1 can' },
    ],
    steps: [
      'Butter bread on one side',
      'Layer cheese, grill until golden',
      'Heat soup on stovetop',
      'Serve sandwiches with soup for dipping',
    ],
    whyReasons: ['Comfort classic', 'Kids devour it', 'Rainy day perfect'],
    estimatedTime: '12 min',
    estimatedCost: '$6',
    imageKey: 'caprese-salad',
  },

  // ============================================
  // CHEAP MODE (6 items, 3 vegetarian)
  // ============================================
  {
    id: 'cheap-1',
    name: 'Rice & Beans',
    mode: 'cheap',
    vegetarian: true,
    allergens: [],
    constraints: ['vegetarian'],
    ingredients: [
      { name: 'Rice', quantity: '1.5 cups' },
      { name: 'Black beans', quantity: '2 cans' },
      { name: 'Cumin', quantity: '1 tsp' },
      { name: 'Lime', quantity: '1' },
    ],
    steps: [
      'Cook rice according to package',
      'Heat beans with cumin and garlic',
      'Layer rice and beans',
      'Squeeze lime on top',
    ],
    whyReasons: ['Complete protein', 'Pantry staples', 'Under $3'],
    estimatedTime: '25 min',
    estimatedCost: '$3',
    imageKey: 'beans-rice',
  },
  {
    id: 'cheap-2',
    name: 'Egg Fried Rice',
    mode: 'cheap',
    vegetarian: true,
    allergens: ['soy', 'eggs'],
    constraints: ['vegetarian', '15_min'],
    ingredients: [
      { name: 'Leftover rice', quantity: '3 cups' },
      { name: 'Eggs', quantity: '3' },
      { name: 'Green onions', quantity: '3' },
      { name: 'Soy sauce', quantity: '2 tbsp' },
    ],
    steps: [
      'Scramble eggs, set aside',
      'Stir-fry cold rice on high heat',
      'Add soy sauce, toss well',
      'Fold in eggs and green onions',
    ],
    whyReasons: ["Uses yesterday's rice", 'Filling and fast', 'Kid-friendly'],
    estimatedTime: '10 min',
    estimatedCost: '$2',
    imageKey: 'egg-fried-rice',
  },
  {
    id: 'cheap-3',
    name: 'Baked Potatoes',
    mode: 'cheap',
    vegetarian: true,
    allergens: ['dairy'],
    constraints: ['vegetarian'],
    ingredients: [
      { name: 'Russet potatoes', quantity: '4 large' },
      { name: 'Butter', quantity: '4 tbsp' },
      { name: 'Sour cream', quantity: '1/2 cup' },
      { name: 'Chives', quantity: 'handful' },
    ],
    steps: [
      'Prick potatoes, microwave 8-10 min',
      'Or bake at 400°F for 45 min',
      'Split open, fluff interior',
      'Top with butter, sour cream, chives',
    ],
    whyReasons: ['Filling comfort food', 'Versatile toppings', 'Under $4'],
    estimatedTime: '15 min',
    estimatedCost: '$4',
    imageKey: 'potato-soup',
  },
  {
    id: 'cheap-4',
    name: 'Ramen Upgrade',
    mode: 'cheap',
    vegetarian: false,
    allergens: ['gluten', 'eggs', 'soy'],
    constraints: ['15_min'],
    ingredients: [
      { name: 'Instant ramen', quantity: '2 packets' },
      { name: 'Egg', quantity: '2' },
      { name: 'Green onions', quantity: '2' },
      { name: 'Sesame oil', quantity: '1 tsp' },
    ],
    steps: [
      'Cook ramen, use half the seasoning',
      'Soft-boil eggs (6 min)',
      'Top ramen with halved eggs',
      'Finish with green onions and sesame oil',
    ],
    whyReasons: ['Dollar store gourmet', 'Protein boost', 'Cozy and fast'],
    estimatedTime: '12 min',
    estimatedCost: '$2',
    imageKey: 'ramen-upgrade',
  },
  {
    id: 'cheap-5',
    name: 'Bean Burritos',
    mode: 'cheap',
    vegetarian: true,
    allergens: ['gluten', 'dairy'],
    constraints: ['vegetarian', '15_min'],
    ingredients: [
      { name: 'Flour tortillas', quantity: '4' },
      { name: 'Refried beans', quantity: '1 can' },
      { name: 'Shredded cheese', quantity: '1 cup' },
      { name: 'Hot sauce', quantity: 'to taste' },
    ],
    steps: [
      'Warm beans in microwave',
      'Spread on tortillas',
      'Add cheese, fold into burritos',
      'Griddle until crispy',
    ],
    whyReasons: ['Pantry hero', 'Portable dinner', 'Customizable heat'],
    estimatedTime: '10 min',
    estimatedCost: '$4',
    imageKey: 'veggie-curry',
  },
  {
    id: 'cheap-6',
    name: 'Pasta Aglio e Olio',
    mode: 'cheap',
    vegetarian: true,
    allergens: ['gluten'],
    constraints: ['vegetarian', '15_min'],
    ingredients: [
      { name: 'Spaghetti', quantity: '12 oz' },
      { name: 'Garlic', quantity: '6 cloves' },
      { name: 'Olive oil', quantity: '1/3 cup' },
      { name: 'Red pepper flakes', quantity: '1/2 tsp' },
    ],
    steps: [
      'Cook pasta, reserve 1 cup pasta water',
      'Sauté sliced garlic in oil until golden',
      'Add pepper flakes, toss with pasta',
      'Add pasta water to emulsify',
    ],
    whyReasons: ['Roman classic', 'Five ingredients', 'Michelin on a budget'],
    estimatedTime: '15 min',
    estimatedCost: '$4',
    imageKey: 'pasta-aglio',
  },
];

// ============================================
// DRM (DINNER RESCUE MODE) — 12 panic meals
// ============================================
export const DRM_MEALS: DrmSeed[] = [
  {
    id: 'drm-1',
    name: 'Cereal & Milk',
    vegetarian: true,
    allergens: ['dairy', 'gluten'],
    constraints: ['no_oven', '15_min', 'kid_safe'],
    ingredients: [
      { name: 'Cereal', quantity: '2 cups' },
      { name: 'Milk', quantity: '1 cup' },
    ],
    steps: ['Pour cereal into bowl', 'Add milk'],
    whyReasons: ['Zero cooking', 'Everyone wins', 'Sometimes dinner is cereal'],
    estimatedTime: '2 min',
    imageKey: 'cereal',
  },
  {
    id: 'drm-2',
    name: 'PB&J Sandwich',
    vegetarian: true,
    allergens: ['gluten', 'nuts'],
    constraints: ['no_oven', '15_min', 'kid_safe'],
    ingredients: [
      { name: 'Bread', quantity: '2 slices' },
      { name: 'Peanut butter', quantity: '2 tbsp' },
      { name: 'Jelly', quantity: '2 tbsp' },
    ],
    steps: ['Spread peanut butter on one slice', 'Spread jelly on the other', 'Press together'],
    whyReasons: ['Childhood classic', 'No judgment here', 'Protein + carbs'],
    estimatedTime: '3 min',
    imageKey: 'toast-pb',
  },
  {
    id: 'drm-3',
    name: 'Cheese & Crackers',
    vegetarian: true,
    allergens: ['dairy', 'gluten'],
    constraints: ['no_oven', '15_min', 'kid_safe'],
    ingredients: [
      { name: 'Cheese', quantity: '4 oz' },
      { name: 'Crackers', quantity: '1 sleeve' },
    ],
    steps: ['Slice cheese', 'Arrange with crackers'],
    whyReasons: ['Charcuterie lite', 'Pairs with wine', 'Snack dinner energy'],
    estimatedTime: '5 min',
    imageKey: 'crackers-cheese',
  },
  {
    id: 'drm-4',
    name: 'Canned Soup',
    vegetarian: false,
    allergens: ['gluten'],
    constraints: ['15_min'],
    ingredients: [
      { name: 'Canned soup', quantity: '1 can' },
      { name: 'Crackers', quantity: 'optional' },
    ],
    steps: ['Open can, pour into pot', 'Heat until simmering', 'Serve with crackers'],
    whyReasons: ['Pantry rescue', 'Warm and comforting', 'No effort required'],
    estimatedTime: '8 min',
    imageKey: 'soup-can',
  },
  {
    id: 'drm-5',
    name: 'Toast & Eggs',
    vegetarian: true,
    allergens: ['gluten', 'eggs'],
    constraints: ['15_min', 'vegetarian'],
    ingredients: [
      { name: 'Bread', quantity: '2 slices' },
      { name: 'Eggs', quantity: '2' },
      { name: 'Butter', quantity: '1 tbsp' },
    ],
    steps: ['Toast bread', 'Fry or scramble eggs', 'Serve together'],
    whyReasons: ['Breakfast for dinner', 'Quick protein', 'Always satisfying'],
    estimatedTime: '8 min',
    imageKey: 'sandwich',
  },
  {
    id: 'drm-6',
    name: 'Chips & Salsa',
    vegetarian: true,
    allergens: [],
    constraints: ['no_oven', '15_min', 'vegetarian', 'kid_safe'],
    ingredients: [
      { name: 'Tortilla chips', quantity: '1 bag' },
      { name: 'Salsa', quantity: '1 jar' },
    ],
    steps: ['Open chips', 'Open salsa', 'Dip and enjoy'],
    whyReasons: ['Zero prep', 'Sharing is caring', 'Valid dinner choice'],
    estimatedTime: '1 min',
    imageKey: 'chips-salsa',
  },
  {
    id: 'drm-7',
    name: 'Instant Noodles',
    vegetarian: false,
    allergens: ['gluten', 'soy'],
    constraints: ['15_min'],
    ingredients: [
      { name: 'Instant noodles', quantity: '1 packet' },
      { name: 'Hot water', quantity: '2 cups' },
    ],
    steps: ['Boil water', 'Add noodles and seasoning', 'Wait 3 minutes'],
    whyReasons: ['Dorm room classic', 'Salty comfort', 'Done in 5 minutes'],
    estimatedTime: '5 min',
    imageKey: 'instant-noodles',
  },
  {
    id: 'drm-8',
    name: 'Yogurt & Granola',
    vegetarian: true,
    allergens: ['dairy', 'nuts'],
    constraints: ['no_oven', '15_min', 'vegetarian'],
    ingredients: [
      { name: 'Greek yogurt', quantity: '1 cup' },
      { name: 'Granola', quantity: '1/2 cup' },
      { name: 'Honey', quantity: '1 tbsp' },
    ],
    steps: ['Scoop yogurt into bowl', 'Top with granola', 'Drizzle honey'],
    whyReasons: ['Protein-packed', 'Feels healthy', 'Sweet but substantial'],
    estimatedTime: '2 min',
    imageKey: 'yogurt-granola',
  },
  {
    id: 'drm-9',
    name: 'Frozen Pizza',
    vegetarian: false,
    allergens: ['dairy', 'gluten'],
    constraints: ['kid_safe'],
    ingredients: [{ name: 'Frozen pizza', quantity: '1' }],
    steps: ['Preheat oven', 'Bake according to package', 'Slice and serve'],
    whyReasons: ['Freezer MVP', 'Everyone agrees', 'Reliable backup'],
    estimatedTime: '20 min',
    imageKey: 'frozen-pizza',
  },
  {
    id: 'drm-10',
    name: 'Apple & Nut Butter',
    vegetarian: true,
    allergens: ['nuts'],
    constraints: ['no_oven', '15_min', 'vegetarian', 'no_dairy'],
    ingredients: [
      { name: 'Apple', quantity: '1' },
      { name: 'Almond butter', quantity: '2 tbsp' },
    ],
    steps: ['Slice apple', 'Dip in almond butter'],
    whyReasons: ['Sweet and salty', 'Surprisingly filling', 'Healthy snack dinner'],
    estimatedTime: '3 min',
    imageKey: 'banana-pb',
  },
  {
    id: 'drm-11',
    name: 'Microwave Burrito',
    vegetarian: false,
    allergens: ['dairy', 'gluten'],
    constraints: ['15_min'],
    ingredients: [{ name: 'Frozen burrito', quantity: '1' }],
    steps: ['Unwrap burrito', 'Microwave 2-3 minutes', 'Add hot sauce if desired'],
    whyReasons: ['Freezer savior', 'Hot and filling', 'Gas station gourmet'],
    estimatedTime: '4 min',
    imageKey: 'grilled-cheese',
  },
  {
    id: 'drm-12',
    name: 'Avocado Toast',
    vegetarian: true,
    allergens: ['gluten'],
    constraints: ['15_min', 'vegetarian', 'no_dairy'],
    ingredients: [
      { name: 'Bread', quantity: '2 slices' },
      { name: 'Avocado', quantity: '1' },
      { name: 'Salt & pepper', quantity: 'to taste' },
      { name: 'Lemon juice', quantity: 'squeeze' },
    ],
    steps: ['Toast bread', 'Mash avocado with fork', 'Spread on toast, season'],
    whyReasons: ['Millennial approved', 'Good fats', 'Trendy but real'],
    estimatedTime: '5 min',
    imageKey: 'oatmeal',
  },
];
