/**
 * Fast Food V2 Recipes
 *
 * Complete recipe database: 33 base + 12 rescue meals
 * Categories: fancy, easy, sweet, rescue
 * Source: Phase 1 content from product PDF
 */

import type { Recipe } from './types';

export const RECIPES: Recipe[] = [
  // ============================================
  // FANCY (8 recipes, high effort/payoff)
  // ============================================
  {
    id: 'fancy-1',
    name: 'Pan-Seared Salmon',
    category: 'fancy',
    vegetarian: false,
    allergens: [],
    constraints: [],
    ingredients: [
      { name: 'Salmon fillet', quantity: '2 pieces' },
      { name: 'Lemon', quantity: '1' },
      { name: 'Butter', quantity: '2 tbsp' },
      { name: 'Fresh dill', quantity: 'handful' },
    ],
    steps: [
      'Pat salmon dry, season with salt and pepper',
      'Heat pan with butter over medium-high',
      'Sear skin-side down for 4 minutes',
      'Flip and cook 3 more minutes',
      'Squeeze lemon, garnish with dill',
    ],
    whyReasons: ['Restaurant quality at home', 'Omega-3 rich', 'Under 20 minutes'],
    time: '18 min',
    cost: '$22',
    image: 'salmon',
    heroSafeFrame: false,
  },
  {
    id: 'fancy-2',
    name: 'Mushroom Risotto',
    category: 'fancy',
    vegetarian: true,
    allergens: ['dairy'],
    constraints: ['vegetarian'],
    ingredients: [
      { name: 'Arborio rice', quantity: '1.5 cups' },
      { name: 'Mixed mushrooms', quantity: '8 oz' },
      { name: 'White wine', quantity: '1/2 cup' },
      { name: 'Parmesan', quantity: '1/2 cup grated' },
      { name: 'Vegetable broth', quantity: '4 cups' },
    ],
    steps: [
      'Sauté mushrooms until golden, set aside',
      'Toast rice in butter for 2 minutes',
      'Add wine, stir until absorbed',
      'Add broth one ladle at a time, stirring',
      'Fold in mushrooms and parmesan',
    ],
    whyReasons: ['Comfort food elevated', 'Vegetarian crowd-pleaser', 'Creamy without cream'],
    time: '35 min',
    cost: '$18',
    image: 'risotto',
    heroSafeFrame: true,
  },
  {
    id: 'fancy-3',
    name: 'Herb-Crusted Chicken',
    category: 'fancy',
    vegetarian: false,
    allergens: ['gluten'],
    constraints: [],
    ingredients: [
      { name: 'Chicken breast', quantity: '2' },
      { name: 'Breadcrumbs', quantity: '1 cup' },
      { name: 'Fresh herbs', quantity: 'mixed' },
      { name: 'Dijon mustard', quantity: '2 tbsp' },
    ],
    steps: [
      'Preheat oven to 400°F',
      'Brush chicken with mustard',
      'Press herb-breadcrumb mixture onto chicken',
      'Bake for 25 minutes until golden',
    ],
    whyReasons: ['Impressive but simple', 'Fresh herbs shine', 'Pairs with anything'],
    time: '35 min',
    cost: '$16',
    image: 'chicken-herbs',
    heroSafeFrame: false,
  },
  {
    id: 'fancy-4',
    name: 'Shrimp Scampi',
    category: 'fancy',
    vegetarian: false,
    allergens: ['shellfish', 'gluten'],
    constraints: ['15_min'],
    ingredients: [
      { name: 'Large shrimp', quantity: '1 lb' },
      { name: 'Garlic', quantity: '4 cloves' },
      { name: 'White wine', quantity: '1/2 cup' },
      { name: 'Butter', quantity: '4 tbsp' },
      { name: 'Red pepper flakes', quantity: 'pinch' },
    ],
    steps: [
      'Melt butter, sauté garlic until fragrant',
      'Add shrimp, cook 2 minutes per side',
      'Deglaze with wine, simmer 2 minutes',
      'Season and plate with crusty bread',
    ],
    whyReasons: ['Elegant but fast', 'Refined flavors', 'Special occasion worthy'],
    time: '15 min',
    cost: '$20',
    image: 'shrimp-scampi',
    heroSafeFrame: false,
  },
  {
    id: 'fancy-5',
    name: 'Beef Tenderloin',
    category: 'fancy',
    vegetarian: false,
    allergens: [],
    constraints: [],
    ingredients: [
      { name: 'Beef tenderloin', quantity: '1.5 lbs' },
      { name: 'Garlic', quantity: '3 cloves' },
      { name: 'Fresh rosemary', quantity: '2 sprigs' },
      { name: 'Olive oil', quantity: '3 tbsp' },
      { name: 'Salt and pepper', quantity: 'to taste' },
    ],
    steps: [
      'Bring beef to room temp, season generously',
      'Sear in hot pan 3 minutes per side',
      'Roast at 400°F for 12-15 min (medium)',
      'Rest 5 minutes, slice and serve',
    ],
    whyReasons: ['Most elegant meal', 'Restaurant showstopper', 'Impressive date night'],
    time: '40 min',
    cost: '$35',
    image: 'beef-tenderloin',
    heroSafeFrame: false,
  },
  {
    id: 'fancy-6',
    name: 'Caprese Salad',
    category: 'fancy',
    vegetarian: true,
    allergens: ['dairy'],
    constraints: ['vegetarian'],
    ingredients: [
      { name: 'Fresh mozzarella', quantity: '8 oz' },
      { name: 'Heirloom tomatoes', quantity: '3 large' },
      { name: 'Fresh basil', quantity: '1 bunch' },
      { name: 'Balsamic vinegar', quantity: '2 tbsp' },
      { name: 'Olive oil', quantity: '3 tbsp' },
    ],
    steps: [
      'Slice tomatoes and mozzarella',
      'Layer alternately on plate with basil',
      'Drizzle balsamic and olive oil',
      'Season with salt and pepper, serve',
    ],
    whyReasons: ['Summer elegance', 'Minimal prep', 'Restaurant quality'],
    time: '10 min',
    cost: '$14',
    image: 'caprese',
    heroSafeFrame: true,
  },
  {
    id: 'fancy-7',
    name: 'Seared Scallops with Lemon Butter',
    category: 'fancy',
    vegetarian: false,
    allergens: ['shellfish'],
    constraints: [],
    ingredients: [
      { name: 'Large sea scallops', quantity: '8' },
      { name: 'Butter', quantity: '4 tbsp' },
      { name: 'Lemon', quantity: '2' },
      { name: 'Garlic', quantity: '2 cloves' },
      { name: 'Fresh parsley', quantity: '1 tbsp' },
    ],
    steps: [
      'Pat scallops dry completely',
      'Sear in hot buttered pan 2 min per side',
      'Remove, melt lemon butter with garlic',
      'Plate scallops, drizzle sauce, garnish',
    ],
    whyReasons: ['Seafood indulgence', 'Surprisingly quick', 'Special occasion'],
    time: '20 min',
    cost: '$28',
    image: 'scallops',
    heroSafeFrame: false,
  },
  {
    id: 'fancy-8',
    name: 'Filet Mignon with Peppercorn Crust',
    category: 'fancy',
    vegetarian: false,
    allergens: [],
    constraints: [],
    ingredients: [
      { name: 'Filet mignon steaks', quantity: '2' },
      { name: 'Black peppercorns', quantity: '2 tbsp' },
      { name: 'Butter', quantity: '3 tbsp' },
      { name: 'Cognac', quantity: '2 tbsp' },
      { name: 'Heavy cream', quantity: '1/4 cup' },
    ],
    steps: [
      'Crush peppercorns, coat steaks',
      'Sear in hot butter 4 min per side',
      'Deglaze with cognac, add cream',
      'Simmer sauce, serve over steaks',
    ],
    whyReasons: ['Most luxurious', 'Date night perfection', 'Celebratory meal'],
    time: '30 min',
    cost: '$40',
    image: 'filet-mignon',
    heroSafeFrame: false,
  },

  // ============================================
  // EASY (8 recipes, quick & repeatable)
  // ============================================
  {
    id: 'easy-1',
    name: 'Classic Cheeseburger',
    category: 'easy',
    vegetarian: false,
    allergens: ['gluten', 'dairy'],
    constraints: [],
    ingredients: [
      { name: 'Ground beef', quantity: '1 lb' },
      { name: 'Burger buns', quantity: '4' },
      { name: 'Cheese', quantity: '4 slices' },
      { name: 'Lettuce and tomato', quantity: 'as desired' },
      { name: 'Condiments', quantity: 'mayo, mustard, ketchup' },
    ],
    steps: [
      'Form 4 patties, season with salt and pepper',
      'Cook in skillet 3-4 min per side',
      'Top with cheese in last minute',
      'Toast buns, assemble with toppings',
    ],
    whyReasons: ['Always works', 'Crowd favorite', 'Fastest fancy'],
    time: '15 min',
    cost: '$12',
    image: 'cheeseburger',
    heroSafeFrame: true,
  },
  {
    id: 'easy-2',
    name: 'Pizza (Sheet Pan Shortcut)',
    category: 'easy',
    vegetarian: true,
    allergens: ['gluten', 'dairy'],
    constraints: ['vegetarian'],
    ingredients: [
      { name: 'Store-bought dough or flatbread', quantity: '1' },
      { name: 'Pizza sauce', quantity: '1/2 cup' },
      { name: 'Mozzarella cheese', quantity: '2 cups' },
      { name: 'Toppings', quantity: 'optional' },
    ],
    steps: [
      'Preheat oven to 425°F',
      'Spread dough on baking sheet',
      'Add sauce, cheese, toppings',
      'Bake 12-15 min until melted',
    ],
    whyReasons: ['Minimal effort', 'Customizable', 'Kids love it'],
    time: '20 min',
    cost: '$8',
    image: 'pizza',
    heroSafeFrame: true,
  },
  {
    id: 'easy-3',
    name: 'BLT Sandwich',
    category: 'easy',
    vegetarian: false,
    allergens: ['gluten', 'dairy'],
    constraints: [],
    ingredients: [
      { name: 'Bacon', quantity: '6 slices' },
      { name: 'Bread', quantity: '2 slices' },
      { name: 'Lettuce and tomato', quantity: 'fresh' },
      { name: 'Mayo', quantity: '2 tbsp' },
    ],
    steps: [
      'Cook bacon until crispy',
      'Toast bread',
      'Layer bacon, lettuce, tomato',
      'Spread mayo, close sandwich',
    ],
    whyReasons: ['Simplicity perfected', 'Summer classic', 'Nostalgic comfort'],
    time: '12 min',
    cost: '$7',
    image: 'blt',
    heroSafeFrame: true,
  },
  {
    id: 'easy-4',
    name: 'Mac & Cheese',
    category: 'easy',
    vegetarian: true,
    allergens: ['dairy', 'gluten'],
    constraints: ['vegetarian'],
    ingredients: [
      { name: 'Pasta', quantity: '1 lb' },
      { name: 'Butter', quantity: '3 tbsp' },
      { name: 'Milk', quantity: '1 cup' },
      { name: 'Cheddar cheese', quantity: '2 cups shredded' },
      { name: 'Salt and pepper', quantity: 'to taste' },
    ],
    steps: [
      'Boil pasta',
      'Melt butter, add milk',
      'Add shredded cheese, melt',
      'Toss pasta with sauce',
    ],
    whyReasons: ['Comfort food king', 'Fast and reliable', 'Universally loved'],
    time: '15 min',
    cost: '$8',
    image: 'mac-cheese',
    heroSafeFrame: true,
  },
  {
    id: 'easy-5',
    name: 'Mashed Potatoes',
    category: 'easy',
    vegetarian: true,
    allergens: ['dairy'],
    constraints: ['vegetarian'],
    ingredients: [
      { name: 'Potatoes', quantity: '2 lbs' },
      { name: 'Butter', quantity: '4 tbsp' },
      { name: 'Milk', quantity: '1/2 cup' },
      { name: 'Salt and pepper', quantity: 'to taste' },
    ],
    steps: [
      'Boil potatoes until soft',
      'Drain and mash',
      'Add butter and milk',
      'Season and serve',
    ],
    whyReasons: ['Pure comfort', 'Pairs with anything', 'Crowd-approved'],
    time: '20 min',
    cost: '$5',
    image: 'mashed-potatoes',
    heroSafeFrame: true,
  },
  {
    id: 'easy-6',
    name: 'Tacos',
    category: 'easy',
    vegetarian: false,
    allergens: ['gluten'],
    constraints: [],
    ingredients: [
      { name: 'Ground beef', quantity: '1 lb' },
      { name: 'Taco seasoning', quantity: '1 packet' },
      { name: 'Taco shells', quantity: '8' },
      { name: 'Lettuce, cheese, salsa', quantity: 'toppings' },
    ],
    steps: [
      'Brown ground beef',
      'Add taco seasoning and water',
      'Simmer 5 minutes',
      'Warm shells, fill with meat and toppings',
    ],
    whyReasons: ['Always reliable', 'Customizable', 'Family night favorite'],
    time: '15 min',
    cost: '$9',
    image: 'tacos',
    heroSafeFrame: true,
  },
  {
    id: 'easy-7',
    name: 'Chili (Basic)',
    category: 'easy',
    vegetarian: false,
    allergens: [],
    constraints: [],
    ingredients: [
      { name: 'Ground beef', quantity: '1.5 lbs' },
      { name: 'Canned beans', quantity: '2 cans' },
      { name: 'Canned tomatoes', quantity: '2 cans' },
      { name: 'Chili seasoning', quantity: '1 packet' },
    ],
    steps: [
      'Brown meat',
      'Add beans, tomatoes, seasoning',
      'Simmer 10-15 minutes',
      'Serve with cheese and sour cream',
    ],
    whyReasons: ['One-pot wonder', 'Satisfying', 'Cold-weather favorite'],
    time: '25 min',
    cost: '$10',
    image: 'chili',
    heroSafeFrame: true,
  },
  {
    id: 'easy-8',
    name: 'French Fries (Oven)',
    category: 'easy',
    vegetarian: true,
    allergens: [],
    constraints: ['vegetarian'],
    ingredients: [
      { name: 'Potatoes', quantity: '2 lbs' },
      { name: 'Olive oil', quantity: '3 tbsp' },
      { name: 'Salt', quantity: 'to taste' },
    ],
    steps: [
      'Cut potatoes into fries',
      'Toss in oil and salt',
      'Bake at 425°F, flip halfway',
      'Crisp and serve',
    ],
    whyReasons: ['Indulgent but healthier', 'Crispy perfection', 'Nostalgic joy'],
    time: '25 min',
    cost: '$4',
    image: 'french-fries',
    heroSafeFrame: true,
  },

  // ============================================
  // CHEAP (5 recipes, budget weeknight meals)
  // ============================================
  {
    id: 'sweet-1',
    name: 'Brownies',
    category: 'cheap',
    vegetarian: true,
    allergens: ['dairy', 'eggs', 'gluten'],
    constraints: ['vegetarian'],
    ingredients: [
      { name: 'Butter', quantity: '1/2 cup' },
      { name: 'Chocolate', quantity: '4 oz' },
      { name: 'Sugar', quantity: '3/4 cup' },
      { name: 'Eggs', quantity: '2' },
      { name: 'Flour', quantity: '1/2 cup' },
    ],
    steps: [
      'Melt butter and chocolate',
      'Mix sugar and eggs',
      'Combine wet and dry',
      'Bake at 350°F for 20-25 min',
    ],
    whyReasons: ['Chocolate satisfaction', 'Foolproof', 'Instant happiness'],
    time: '40 min',
    cost: '$6',
    image: 'brownies',
    heroSafeFrame: true,
  },
  {
    id: 'sweet-2',
    name: 'Apple Pie',
    category: 'cheap',
    vegetarian: true,
    allergens: ['dairy', 'gluten'],
    constraints: ['vegetarian'],
    ingredients: [
      { name: 'Apples', quantity: '6 large' },
      { name: 'Pie crust', quantity: '2' },
      { name: 'Sugar', quantity: '1/2 cup' },
      { name: 'Cinnamon', quantity: '1 tsp' },
      { name: 'Butter', quantity: '2 tbsp' },
    ],
    steps: [
      'Slice and toss apples with sugar and cinnamon',
      'Fill crust, dot with butter, cover',
      'Bake at 375°F for 40-45 min',
      'Cool before serving',
    ],
    whyReasons: ['Quintessential comfort', 'Homemade warmth', 'Classic American'],
    time: '60 min',
    cost: '$9',
    image: 'apple-pie',
    heroSafeFrame: true,
  },
  {
    id: 'sweet-3',
    name: 'Ice Cream Sundae',
    category: 'cheap',
    vegetarian: true,
    allergens: ['dairy', 'eggs'],
    constraints: ['vegetarian'],
    ingredients: [
      { name: 'Ice cream', quantity: '2 scoops' },
      { name: 'Chocolate syrup', quantity: '2 tbsp' },
      { name: 'Whipped cream', quantity: 'dollop' },
      { name: 'Toppings', quantity: 'sprinkles, nuts, etc.' },
    ],
    steps: [
      'Scoop ice cream into bowl',
      'Add chocolate syrup',
      'Top with whipped cream',
      'Add sprinkles and serve',
    ],
    whyReasons: ['Pure joy', 'Instant treat', 'Nostalgia in a bowl'],
    time: '5 min',
    cost: '$5',
    image: 'sundae',
    heroSafeFrame: true,
  },
  {
    id: 'sweet-4',
    name: 'Cereal Bowl (Elevated)',
    category: 'cheap',
    vegetarian: true,
    allergens: ['dairy'],
    constraints: ['vegetarian'],
    ingredients: [
      { name: 'Cereal', quantity: '1 cup' },
      { name: 'Milk', quantity: '1 cup' },
      { name: 'Fruit', quantity: 'fresh' },
      { name: 'Honey', quantity: 'optional' },
    ],
    steps: [
      'Pour cereal into bowl',
      'Add milk',
      'Add fresh fruit',
      'Eat immediately',
    ],
    whyReasons: ['Simplest sweet', 'Breakfast crossover', 'Late-night ok'],
    time: '2 min',
    cost: '$3',
    image: 'cereal-bowl',
    heroSafeFrame: true,
  },
  {
    id: 'sweet-5',
    name: 'Scrambled Eggs (Breakfast Sweet/Neutral)',
    category: 'cheap',
    vegetarian: true,
    allergens: ['dairy', 'eggs'],
    constraints: ['vegetarian'],
    ingredients: [
      { name: 'Eggs', quantity: '3' },
      { name: 'Butter', quantity: '1 tbsp' },
      { name: 'Salt and pepper', quantity: 'to taste' },
    ],
    steps: [
      'Crack eggs into bowl, beat',
      'Melt butter in pan',
      'Pour in eggs, stir gently',
      'Cook until soft-set, serve',
    ],
    whyReasons: ['Any-time meal', 'Protein-packed', 'Comfort classic'],
    time: '8 min',
    cost: '$2',
    image: 'scrambled-eggs',
    heroSafeFrame: true,
  },

  // ============================================
  // RESCUE (12 panic meals, zero friction)
  // ============================================
  {
    id: 'rescue-1',
    name: 'Rice Bowl',
    category: 'rescue',
    vegetarian: true,
    allergens: [],
    constraints: [],
    ingredients: [
      { name: 'Cooked rice', quantity: 'use leftovers' },
      { name: 'Protein (chicken, beef, eggs)', quantity: 'any' },
      { name: 'Sauce (soy, teriyaki, etc.)', quantity: 'any' },
      { name: 'Frozen veggies', quantity: 'optional' },
    ],
    steps: [
      'Heat rice',
      'Add protein',
      'Add sauce',
      'Mix and eat',
    ],
    whyReasons: ['Instant satisfaction', 'Always available', 'No thinking'],
    time: '5 min',
    cost: '-',
    image: 'rice-bowl',
    heroSafeFrame: true,
  },
  {
    id: 'rescue-2',
    name: 'Pasta + Red Sauce',
    category: 'rescue',
    vegetarian: true,
    allergens: ['gluten', 'dairy'],
    constraints: [],
    ingredients: [
      { name: 'Pasta', quantity: 'dry' },
      { name: 'Jarred sauce', quantity: '1 jar' },
      { name: 'Parmesan', quantity: 'optional' },
    ],
    steps: [
      'Boil pasta',
      'Heat jar sauce',
      'Combine and eat',
    ],
    whyReasons: ['Fastest dinner', 'Always works', 'Pantry staple'],
    time: '10 min',
    cost: '-',
    image: 'pasta-sauce',
    heroSafeFrame: true,
  },
  {
    id: 'rescue-3',
    name: 'Quesadillas',
    category: 'rescue',
    vegetarian: true,
    allergens: ['dairy', 'gluten'],
    constraints: [],
    ingredients: [
      { name: 'Tortillas', quantity: '2' },
      { name: 'Cheese', quantity: '1 cup' },
      { name: 'Protein (optional)', quantity: 'any' },
    ],
    steps: [
      'Add cheese to tortilla',
      'Cook both sides in pan',
      'Slice and eat',
    ],
    whyReasons: ['Minimal effort', 'Customizable', 'Done in 5 min'],
    time: '5 min',
    cost: '-',
    image: 'quesadillas',
    heroSafeFrame: true,
  },
  {
    id: 'rescue-4',
    name: 'Grilled Cheese',
    category: 'rescue',
    vegetarian: true,
    allergens: ['dairy', 'gluten'],
    constraints: ['vegetarian'],
    ingredients: [
      { name: 'Bread', quantity: '2 slices' },
      { name: 'Cheese', quantity: '2 slices' },
      { name: 'Butter', quantity: '1 tbsp' },
    ],
    steps: [
      'Butter bread',
      'Add cheese',
      'Cook both sides until golden',
    ],
    whyReasons: ['Instant comfort', 'Nothing fancy', 'Works every time'],
    time: '5 min',
    cost: '-',
    image: 'grilled-cheese',
    heroSafeFrame: true,
  },
  {
    id: 'rescue-5',
    name: 'Frozen Pizza (or Fast)',
    category: 'rescue',
    vegetarian: true,
    allergens: ['dairy', 'gluten'],
    constraints: [],
    ingredients: [
      { name: 'Frozen pizza or store dough', quantity: '1' },
    ],
    steps: [
      'Preheat oven',
      'Add pizza',
      'Bake',
    ],
    whyReasons: ['Zero thinking', 'Reliable option', 'No shame'],
    time: '12 min',
    cost: '-',
    image: 'frozen-pizza',
    heroSafeFrame: true,
  },
  {
    id: 'rescue-6',
    name: 'Breakfast for Dinner',
    category: 'rescue',
    vegetarian: true,
    allergens: ['dairy', 'eggs', 'gluten'],
    constraints: [],
    ingredients: [
      { name: 'Eggs', quantity: '2-3' },
      { name: 'Toast', quantity: '1-2 slices' },
      { name: 'Bacon or sausage', quantity: 'optional' },
    ],
    steps: [
      'Cook eggs',
      'Toast bread',
      'Cook meat if using',
      'Plate and eat',
    ],
    whyReasons: ['Any-time meal', 'Protein-rich', 'Nostalgic'],
    time: '10 min',
    cost: '-',
    image: 'breakfast',
    heroSafeFrame: true,
  },
  {
    id: 'rescue-7',
    name: 'Lightning Chili',
    category: 'rescue',
    vegetarian: false,
    allergens: [],
    constraints: [],
    ingredients: [
      { name: 'Ground beef', quantity: 'brown quick' },
      { name: 'Canned chili or beans', quantity: 'heat' },
      { name: 'Seasoning', quantity: 'add to taste' },
    ],
    steps: [
      'Brown meat',
      'Add canned chili',
      'Heat 5 min',
      'Serve',
    ],
    whyReasons: ['Cheating allowed', 'Still tasty', 'Very quick'],
    time: '10 min',
    cost: '-',
    image: 'chili-quick',
    heroSafeFrame: true,
  },
  {
    id: 'rescue-8',
    name: 'Chicken Noodle Soup',
    category: 'rescue',
    vegetarian: false,
    allergens: ['gluten', 'dairy'],
    constraints: [],
    ingredients: [
      { name: 'Chicken broth', quantity: '4 cups' },
      { name: 'Noodles', quantity: 'any' },
      { name: 'Cooked chicken', quantity: 'deli or canned' },
      { name: 'Veggies', quantity: 'carrots, celery optional' },
    ],
    steps: [
      'Boil broth',
      'Add noodles',
      'Add chicken and veggies',
      'Simmer 5 min',
    ],
    whyReasons: ['Comforting', 'Healing', 'Instant warmth'],
    time: '15 min',
    cost: '-',
    image: 'chicken-soup',
    heroSafeFrame: true,
  },
  {
    id: 'rescue-9',
    name: 'Thursday Night Soup (Leftover Soup)',
    category: 'rescue',
    vegetarian: true,
    allergens: [],
    constraints: [],
    ingredients: [
      { name: 'Leftovers', quantity: 'combine' },
      { name: 'Broth', quantity: 'any' },
      { name: 'Seasoning', quantity: 'to taste' },
    ],
    steps: [
      'Combine leftovers',
      'Add broth',
      'Heat and season',
      'Eat',
    ],
    whyReasons: ['Zero waste', 'Cleanup genius', 'Hidden gem'],
    time: '10 min',
    cost: '-',
    image: 'leftover-soup',
    heroSafeFrame: true,
  },
  {
    id: 'rescue-10',
    name: 'Easy Nachos',
    category: 'rescue',
    vegetarian: true,
    allergens: ['dairy'],
    constraints: [],
    ingredients: [
      { name: 'Chips', quantity: '1 bag' },
      { name: 'Cheese', quantity: 'melted' },
      { name: 'Meat or beans', quantity: 'optional' },
      { name: 'Salsa and toppings', quantity: 'any' },
    ],
    steps: [
      'Lay chips',
      'Add cheese',
      'Bake/microwave until melted',
      'Add toppings',
    ],
    whyReasons: ['Fun food', 'No thinking', 'Crowd pleaser'],
    time: '5 min',
    cost: '-',
    image: 'nachos',
    heroSafeFrame: true,
  },
  {
    id: 'rescue-11',
    name: 'Spicy Beef Ramen',
    category: 'rescue',
    vegetarian: false,
    allergens: ['gluten'],
    constraints: [],
    ingredients: [
      { name: 'Ramen noodles', quantity: '1 package' },
      { name: 'Ground beef', quantity: 'cooked' },
      { name: 'Broth', quantity: 'from package or other' },
      { name: 'Chili paste or seasoning', quantity: 'to taste' },
      { name: 'Egg (optional)', quantity: '1' },
    ],
    steps: [
      'Boil noodles',
      'Cook beef',
      'Add broth and seasoning',
      'Combine and eat',
    ],
    whyReasons: ['Student favorite', 'Very fast', 'Spicy satisfaction'],
    time: '10 min',
    cost: '-',
    image: 'ramen',
    heroSafeFrame: true,
  },
  {
    id: 'rescue-12',
    name: 'Cereal + Toast (Actual Panic Mode)',
    category: 'rescue',
    vegetarian: true,
    allergens: ['dairy', 'gluten'],
    constraints: [],
    ingredients: [
      { name: 'Cereal', quantity: 'any' },
      { name: 'Milk', quantity: 'any' },
      { name: 'Bread', quantity: 'toast it' },
      { name: 'Butter or jam', quantity: 'optional' },
    ],
    steps: [
      'Pour cereal',
      'Toast bread',
      'Assemble',
      'Eat quickly',
    ],
    whyReasons: ['When everything fails', 'No cooking', 'Honest meal'],
    time: '3 min',
    cost: '-',
    image: 'cereal-toast',
    heroSafeFrame: true,
  },
];

// Active exports
export const DRM_MEALS = RECIPES.filter(r => r.category === 'rescue');

// Legacy exports for backward compatibility
export const RECIPE_SEEDS = RECIPES;
export const DRM_SEEDS = DRM_MEALS;
